# Generated by Django 5.0.3 on 2024-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='url для пользователя')),
                ('description', models.TextField(max_length=500, verbose_name='содержимое')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='photo_blog/', verbose_name='изображение')),
                ('product_date', models.DateTimeField(blank=True, null=True, verbose_name='дата создания')),
                ('blog_is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блоговая запись',
                'verbose_name_plural': 'блоговые записи',
                'ordering': ('blog_title',),
            },
        ),
    ]
