# Generated by Django 5.0.3 on 2024-06-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='product_date',
            new_name='blog_date',
        ),
    ]
