# Generated by Django 5.0.3 on 2024-05-05 09:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='почта клиента')),
                ('client_fullname', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('comment', models.CharField(blank=True, verbose_name='комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='NewsletterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_topic', models.CharField(max_length=500, verbose_name='тема рассылки')),
                ('newsletter_message', models.TextField(max_length=30, verbose_name='сообщение рассылки')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Тема рассылки',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Выбрать время')),
                ('frequency', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=255, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('running', 'Запущена')], max_length=255, verbose_name='Статус')),
                ('start_at', models.DateTimeField(default=datetime.datetime(2024, 5, 5, 12, 8, 53, 745049), verbose_name='дата начала')),
                ('finish_at', models.DateTimeField(default=datetime.datetime(2024, 6, 4, 9, 8, 53, 744037, tzinfo=datetime.timezone.utc), verbose_name='дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('clients', models.ManyToManyField(to='newsletter.client', verbose_name='Клиент')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newslettermessage', verbose_name='Рассылка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Рассылка',
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='последняя попытка')),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
                ('server_response', models.CharField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newslettersettings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ('last_tried_at',),
            },
        ),
    ]
