# Generated by Django 5.0.3 on 2024-05-22 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_alter_newslettersettings_finish_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersettings',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 12, 15, 4, 115271, tzinfo=datetime.timezone.utc), verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 15, 15, 4, 130903), verbose_name='дата начала'),
        ),
    ]
