# Generated by Django 5.0.3 on 2024-06-03 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_newslettersettings_finish_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersettings',
            options={'permissions': [('set_status', 'Can change status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 9, 15, 24, 699001, tzinfo=datetime.timezone.utc), verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 12, 15, 24, 699001), verbose_name='дата начала'),
        ),
    ]
